version: '3.3'
services:
  clubapi:
    build: .
    #dns:
    #- 8.8.8.8
    #- 8.8.4.4
    container_name: main_api
    ports:
      - '3001:3001'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    volumes:
      - /app/node_modules
    command: npm run start
